// @ts-nocheck

import { Icon } from "@iconify/react";
import JoditEditor from "jodit-react";
import { useEffect, useRef, useState } from "react";
import { Collapse } from "react-bootstrap";
import { useSelector } from "react-redux";
import useFetch from "use-http";
import { appendText } from "../../../components/AutoCompleteComp/AppendData";
import AutoComplete from "../../../components/AutoCompleteComp/AutoComplete";
import TextGenerateModal from "../../../components/Modal/TextGenerateModal";
import {
  $collapser,
  savingData,
  selectSection,
  updateData,
  updateResume,
} from "../../../services";
import "../resumeStyle.scss";
const Summary = ({ onDelete, docId, info, setChangeState }: any) => {
  const editor = useRef(null);
  const ref = useRef(null);
  const [editName, setEditName] = useState(false);
  const { response, post, loading, get, data: repos, put } = useFetch();
  const [visible, setVisible] = useState(false);
  const [sectionTitle, setSectionTitle] = useState(info.title);
  const [autoCompletionText, setAutoCompletionText] = useState("");
  const [modalShow, setModalShow] = useState(false);

  const [modalContentShow, setModalContentShow] = useState({
    sentenceWriterModal: false,
    aiWriterModal: false,
    selectedIndex: 0,
  });
  const [content, setContent] = useState(info.description);
  const config = {
    readonly: false,
    enableDragAndDropFileToEditor: true,
    buttons: [
      "bold",
      "italic",
      "underline",
      "justify",
      "left",
      "right",
      "ul",
      "ol",
      "link",
    ],

    removeButtons: [
      "fullsize",
      "fontsize",
      "eraser",
      "font",
      "brush",
      "paragraph",
      "file",
      "eraser",
      "source",
      "hr",
      "image",
      "table",
      "formatpainter",
    ],
    showXPathInStatusbar: false,
    showCharsCounter: false,
    showWordsCounter: false,
    toolbarAdaptive: false,
    toolbarSticky: true,
    askBeforePasteHTML: false,
    allowTabNavigtion: false,
    height: 200,
  };

  const [section, setSectionOpener] = useState("");
  const auth: any = useSelector((store: any) => store.auth);
  useEffect(() => {
    const sub$ = $collapser.subscribe((v: string) => {
      setSectionOpener(v);
    });
    return () => {
      sub$.unsubscribe();
    };
  }, []);
  useEffect(() => {
    info.description = content;
    updateResume({ summary: info });

    const sub$ = $collapser.subscribe((v: string) => {
      setSectionOpener(v);
    });
    return () => {
      sub$.unsubscribe();
    };
  }, [content]);

  const updateValues = (data) => {
    data.title = sectionTitle;
    if (auth.isLoggedIn) {
      postSummary(data);
    } else {
      updateData({
        summary: data,
      });
      savingData("saved");
    }
  };

  let _setTimeOut = null;
  const onFormChange = (data) => {
    if (_setTimeOut) clearTimeout(_setTimeOut);
    info.description = data;
    updateResume({ summary: info });
    savingData("saving...");
    _setTimeOut = setTimeout(updateValues(info), 1000);
  };

  const postSummary = async (data) => {
    const res = await put(`resume/update/${docId}`, {
      summary: data,
    });
    savingData("saved");
  };
  const changeTitle = (e: any) => {
    e.stopPropagation();
    setEditName(false);
    info.description = content;
    info.title = sectionTitle;
    updateResume({ summary: info });

    if (auth.isLoggedIn) {
      postSummary();
      updateResume({ summary: info });
    } else {
      updateData({
        summary: info,
      });
    }
  };
  const updateContent = (v: string) => {
    info.description = v;

    info.title = sectionTitle;
    setContent(v);
    updateResume({ summary: info });
    if (!auth.isLoggedIn) {
      updateData({
        summary: info,
      });
    } else {
      const postSummary = async (data) => {
        const res = await put(`resume/update/${docId}`, {
          summary: data,
        });
      };
      postSummary(info);
    }
  };
  useEffect(() => {
    if (autoCompletionText) {
      appendText(autoCompletionText);
    }
  }, [autoCompletionText]);
  const handleEditorChange = (newContent) => {
    const elem = document.querySelector(".jodit-wysiwyg>p");
    if (autoCompletionText) {
      const lastChar = newContent
        .replace(/(<([^>]+)>)/gi, "")
        ?.replace(/(&nbsp;|\s)+/g, " ")
        .slice(-1);

      if (lastChar === " " || lastChar === "\t" || lastChar === "\n") {
        const autoGeneratedText = "Hello, world!";

        document.getElementById("text-append")?.remove();

        let completeText = `${content
          .replace(/(<([^>]+)>)/gi, "")
          ?.replace(/(&nbsp;|\s)+/g, " ")
          .trim()} ${autoCompletionText}`;
        updateContent(completeText);
        setAutoCompletionText("");
      }
    } else {
      setAutoCompletionText("");
    }
  };

  let isOpend = section === "summary";
  isOpend ? setChangeState(ref) : null;
  return (
    <>
      <div className="resume-box" ref={ref}>
        <div
          className="box-header d-flex justify-content-between"
          onClick={() => {
            selectSection("summary");
          }}
          aria-controls="summary"
          aria-expanded={section === "summary"}>
          <div
            className="header-left d-inline-flex align-items-center"
            onClick={(e) => {
              e.stopPropagation();
            }}>
            <div className="figure-icon">
              <Icon icon="ph:notepad" />
            </div>
            <h5
              onClick={(e) => {
                e.stopPropagation();
              }}>
              {editName ? (
                <input
                  type="text"
                  defaultValue={sectionTitle}
                  onChange={(e) => setSectionTitle(e.target.value)}
                />
              ) : (
                `${sectionTitle}`
              )}
              <button
                className={
                  editName ? "edit-button d-none" : "edit-button edit-btn"
                }
                onClick={(e) => {
                  e.stopPropagation();
                  setEditName(true);
                }}>
                <Icon icon="eva:edit-2-outline" />
              </button>
              <button
                className={editName ? "edit-button" : "edit-button d-none"}
                onClick={(e) => changeTitle(e)}>
                <Icon icon="charm:circle-tick" />
              </button>
            </h5>
          </div>
          <div className="header-right">
            <button
              className="delete-button"
              onClick={(e) => {
                e.stopPropagation();
              }}>
              <Icon icon="bi:trash" hFlip={true} onClick={onDelete} />
            </button>
          </div>
        </div>
        {isOpend ? (
          <Collapse in={section === "summary"}>
            <form className="box-body" id="summary">
              <div className="row">
                <div className="col-lg-12">
                  <div className="content-editor">
                    <label>Professional Summary</label>
                    <JoditEditor
                      ref={editor}
                      defaultValue={content}
                      value={content}
                      tabIndex={1}
                      config={config}
                      onBlur={(newContent) => {
                        setContent(newContent);
                        onFormChange(newContent);
                      }}
                      onChange={handleEditorChange}
                    />
                    {
                      <AutoComplete
                        toolType="sentence_autocomplete_summary"
                        text={content}
                        secName="summary"
                        textHandler={updateContent}
                        ghostText={setAutoCompletionText}
                      />
                    }
                    <div className="editor-buttons">
                      <a
                        className="btn btn-white"
                        onClick={() => {
                          setModalShow(true);
                          setModalContentShow({
                            sentenceWriterModal: true,
                            aiWriterModal: false,
                          });
                        }}>
                        <Icon icon="ph:keyboard" />
                        <span>Sentence Rewriter</span>
                      </a>
                      <a
                        className="btn btn-light-blue"
                        onClick={() => {
                          setModalShow(true);
                          setModalContentShow({
                            sentenceWriterModal: false,
                            aiWriterModal: true,
                          });
                        }}>
                        <Icon icon="eva:flash-outline" />
                        <span> AI Writer</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </Collapse>
        ) : null}
      </div>
      <TextGenerateModal
        secName="summary"
        text={content}
        setText={updateContent}
        showModal={modalShow}
        showModalHandler={setModalShow}
        modalContentShow={modalContentShow}
      />
    </>
  );
};
export default Summary;
