export const GUARDIAN_TWEETS = "GUARDIAN/TWEETS";
export const GUARDIAN_CHANGE_STATUS_TWEET = "GUARDIAN/TWEET/CHANGE_STATUS";
export const USER_GET_TWEET = "USER/GET_TWEET";
export const USER_CREATE_TWEET = "USER/CREATE_TWEET";
export const GUARDIAN_SKIP_TWEET = "GUARDIAN/SKIP_TWEET";
